---
language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements-dev.txt

script: 
  - pylama -F netmiko_tools/netmiko-grep
  - pylama -F netmiko_tools/netmiko-show
